### ISSUE TITLE
add config.plist

### ISSUE THREAD

**Issue by alifnuryana** [SuhailSherief/ThinkPad-x260-macOS-OpenCore#1]
can you add config.plist file?

**Comment by SuhailSherief** [comment]
Oh! Sure, I'm still building the repository, trying a clean architecture this time, so it may take some time. I already have all the EFI files ready. If you need I can share you in a gdrive. Let me know buddy.

**Comment by SuhailSherief** [comment]
> can you add config.plist file?

Oh! Sure, I'm still building the repository, trying a clean architecture so it may take some time. I already have all the EFI files ready. If you need I can share you in a gdrive. Let me know buddy.

**Comment by mr-r1z3nt0sh** [comment]
Hello, could you send me the plis in gdrive?

**Comment by SuhailSherief** [comment]
> Hello, could you send me the plis in gdrive?

Here you go ! It's fully functional EFI for x260 and possibly other same gen models.

https://drive.google.com/drive/folders/1JIOjc24TlZHOnO1-PcQ-L1GihkIPRvuM?usp=sharing

Thank you for the support guys.

**Comment by SuhailSherief** [comment]
I'm closing this issue now since the shared EFI contains config.plist

**Comment by mr-r1z3nt0sh** [comment]
I found a problem, missing audiodxe.efi

**Comment by SuhailSherief** [comment]
> I found a problem, missing audiodxe.efi

please check /EFI/OC/Drivers you have it there.
BTW if you are using x260 just copy this efi and boot it will run totally fine.
If you have more doubts contact me on discord LuciFer#1423

**Comment by mr-r1z3nt0sh** [comment]
> please check /EFI/OC/Drivers you have it there.
> BTW if you are using x260 just copy this efi and boot it will run totally fine.
> If you have more doubts contact me on discord 

it's not in your folder, but i already added it from dortania so it's starting right now, thanks

**Comment by mr-r1z3nt0sh** [comment]
> > please check /EFI/OC/Drivers you have it there.
> > BTW if you are using x260 just copy this efi and boot it will run totally fine.
> > If you have more doubts contact me on discord 
> 
> it's not in your folder, but i already added it from dortania so it's starting right now, thanks 

![image](https://user-images.githubusercontent.com/51177543/179915536-3a592ee7-13f9-402d-9537-cfa2f3c218c5.png)

**Comment by SuhailSherief** [comment]
> it's not in your folder, but i already added it from dortania so it's starting right now, thanks

oh that's great, I'll update it soon.
