### ISSUE TITLE
hdmi wont work

### ISSUE THREAD

**Issue by Capestick** [SuhailSherief/ThinkPad-x260-macOS-OpenCore#10]
hi there hdmi wont work. i try connect it nothing happens and when i disconnect it the laptop goes black and then back thanks for any ideas!

**Comment by SuhailSherief** [comment]
which build of MacOS do you use buddy ?
Please use build 12.6.2 I'm currently preparing EFI for Ventura.
If you need a snapshot of 12.6.2 let me know :)

**Comment by Capestick** [comment]
hi there. im using 12.6.3. yeah if a snapshot would fix it please send it haha. thanks!

**Comment by SuhailSherief** [comment]
Sure thing gimme some hours

**Comment by Capestick** [comment]
👍 thanks alot

**Comment by SuhailSherief** [comment]
https://dortania.github.io/OpenCore-Install-Guide/installer-guide/mac-install.html#command-line-software-update-utility

**Comment by SuhailSherief** [comment]
ahh JN took the guide from dortainia to look up how to install previous versions of MacOS the guide will lead you to 12.6.2. How about other features tho buddy they work or some problems you face ?

**Comment by Capestick** [comment]
thanks again. yeah everything works HDMI works after a couple of tries but yeah 12.6.2

**Comment by Capestick** [comment]
and if i do this will i lose my data?

**Comment by SuhailSherief** [comment]
> and if i do this will i lose my data?

Definitely you will loose so please take a backup

**Comment by SuhailSherief** [comment]
> thanks again. yeah everything works HDMI works after a couple of tries but yeah 12.6.2

Happens the same with hdmi and DisplayPort. macOS definitely comes with some trade offs but yeah it definitely works after 1 or 2 tries. Same case in 12.6.2 too. 

One tip tho is to turn on external monitor first and switch the monitor input source to HDMI or DP, once you log in into your Mac and in your home screen plug the HDMI or DP to your laptop. What I mean by that is don't cold boot or reboot with HDMI or DP plugged into your laptop :) this way it will work on the first try itself. Thanks for letting me know that other things work great. Give me a confirmation that you are good to go and I'll close this issue.
