### ISSUE TITLE
Sequoia?

### ISSUE THREAD

**Issue by gustavsgoldbergs** [SuhailSherief/ThinkPad-x260-macOS-OpenCore#14]
when and if

**Comment by SuhailSherief** [comment]
Hi! been busy for few months so I doubt if I can. But feel free to contribute. I'll add you to contributors in case you are willing to :)

**Comment by latiefkhan** [comment]
still waiting for Sequoia

**Comment by SuhailSherief** [comment]
> still waiting for Sequoia

Sadly, my laptop died after aging well so I can't actively maintain this repository. You are free to raise PR if you have a working EFI. Good day!
