### ISSUE TITLE
HDMI issues with ultra dock

### ISSUE THREAD

**Issue by mintyleaf** [SuhailSherief/ThinkPad-x260-macOS-OpenCore#2]
Hey!
Just used your config to boot up macOS on my x260
Everything went well, except HDMI flickering via the dock (HDMI via laptop itself is working fine)
There are an issue somewhat addressing to that: https://github.com/simprecicchiani/ThinkPad-T460s-macOS-OpenCore/issues/14
I'll try to mess around with WhateverGreen kext somehow

**Comment by mintyleaf** [comment]
After fiddling around I got the knowledge that dock HDMI is routed via DP, which is broken
But, that workaround is working, even with hot swap from the dock after it!
https://github.com/simprecicchiani/ThinkPad-T460s-macOS-OpenCore/issues/14#issuecomment-917641995

**Comment by SuhailSherief** [comment]
Great to hear that mate! will leave you pinned here in comments
