### ISSUE TITLE
Monterey bluetooth fix

### ISSUE THREAD

**Issue by mintyleaf** [SuhailSherief/ThinkPad-x260-macOS-OpenCore#3]
https://github.com/simprecicchiani/ThinkPad-T460s-macOS-OpenCore/issues/150#issuecomment-1328252628

**Comment by SuhailSherief** [comment]
Exactly, I actually forgot to add that buddy. You definitely get a pin. Fork and send a pull request buddy, if you can. Thanks a lot in advance. I'll add you in contributors list <3

**Comment by mintyleaf** [comment]
> Exactly, I actually forgot to add that buddy. You definitely get a pin. Fork and send a pull request buddy, if you can. Thanks a lot in advance. I'll add you in contributors list <3

<3

I'll add pr later, I'm also updated the whole setup to 0.8.6 open core, some latest (at the moment, not for now, lol) kexts, which is grabbed from t460 repo

**Comment by mintyleaf** [comment]
a few notes on this issue

- I actually had only one time hash mismatch error just randomly popping, and purging cache and repowering bluetooth still was a thing
- Today, after a wake (bluetooth was ok after wakes before, so that is not a regular case I guess), suddenly, bluetooth seemed to be broken (without hash mismatch error, maybe it's just didn't pop at all)
I tried to repower it and purge cache - but no luck
I really didn't wanted to go for a reboot, so I tried to dig
Killing bluetoothd and trying to stop/start it didn't get any results
I tried to purge cache then and sleep/wake again - no luck, and after that bluetoothd started failing with -11 segfault error according to launchctl print
So.. I remembered, that unloading and loading service, instead of stop/start it can do the trick - and it did
So if you suddenly have some rare bluetooth issues - I think that fully reloading bluetoothd is a good way to fix it

**Comment by mbledkowski** [comment]
Bluetooth is not working on my X260. What is the command to reload bluetoothd? When I use `sudo launchctl reboot bluetooth` system instantaneous crashes.

**Comment by SuhailSherief** [comment]
> Bluetooth is not working on my X260. What is the command to reload bluetoothd? When I use `sudo launchctl reboot bluetooth` system instantaneous crashes.

which EFI are you using now buddy ? Make sure you use ones from the latest release. Check the releases page for the updated EFI. You can also ping me anytime in discord my id is suhailsherief

**Comment by mbledkowski** [comment]
I downloaded EFI from branch ventura. Using the latest macOS

**Comment by SuhailSherief** [comment]
> I downloaded EFI from branch ventura. Using the latest macOS

Yeah I'll update it now. Till then use the EFI on releases page. I updated it just 3 days back and its working perfectly. I forgot to update the repo tho
