### ISSUE TITLE
Wi-Fi won't work on Monterey

### ISSUE THREAD

**Issue by rynesPT** [SuhailSherief/ThinkPad-x260-macOS-OpenCore#6]
Hi! I've been using this EFI for my x260 and everything's working wonderfully except for the Wi-Fi.
I've tried Airportltlwm-Monterey and itlwm but they don't seem to work. Used HeliPort for itlwm and it said that it wasn't running. And added the necessary lines to the config.plist My card's the same as yours and I've tried multiple times before opening this issue. Could you tell me what I could do to fix this? I've done a clean install of Monterey 12.6 and haven't been able to fix this. I attached photos of the problem and my config.plist.

Thank you so much for sharing your EFI and explaining everything so well!

![IMG_0639](https://user-images.githubusercontent.com/119418594/204604259-2fa994e8-b5db-4091-8877-962ee4125fb3.JPEG)
![IMG_0640](https://user-images.githubusercontent.com/119418594/204604278-4c8aac66-d828-490f-a624-565b9b67be43.JPEG)
![IMG_0641](https://user-images.githubusercontent.com/119418594/204604285-6c3d6023-eaec-45f2-b045-e35f421d44f0.JPEG)
[config.zip](https://github.com/SuhailSherief/ThinkPad-x260-macOS-OpenCore/files/10115742/config.zip)

**Comment by mintyleaf** [comment]
very strange, so you have intel 8260 wireless adapter, which is worked before, right?
according to your config seems like that all good

it will be nice to have exact specs and other stuff

**Comment by rynesPT** [comment]
Well, now it works. I don't remember what I did but it work but I can't seem to get the Wi-Fi to connect and as soon as I put in a password it says "Could not join "xxxxxx". The network could not be found." but the Bluetooth works perfectly

I have an i5-6300U, HD 520, 480GB SSD, the intel 8260.

EDIT:
Appears to only do that if I boot with a LAN cable, which is confusing. If I don't boot with it, the problem will be exact same one as the photos.

**Comment by mintyleaf** [comment]
> Well, now it works. I don't remember what I did but it work but I can't seem to get the Wi-Fi to connect and as soon as I put in a password it says "Could not join "xxxxxx". The network could not be found." but the Bluetooth works perfectly
> 
> I have an i5-6300U, HD 520, 480GB SSD, the intel 8260.
> 
> EDIT: Appears to only do that if I boot with a LAN cable, which is confusing. If I don't boot with it, the problem will be exact same one as the photos.

it's a really really strange thing is going there)
I have the same cpu/card, and with exact that config I'm successfully downloaded 12 gig Monterey system in installer through wifi, and don't ever had any issues with it

did you tried other wifi network?
you can also look at my PR with 0.8.6 update there, just fully replace all the EFI by that
I remember I updated itlwm kexts there, and other stuff (sip disabled by default! it done in nvram section)
maybe that just.. gonna work I guess

**Comment by rynesPT** [comment]
Sorry for the dumb question but how do I download the PR? And thanks for the help!

Edit: Just downloaded it! Going to try it out. :D

**Comment by rynesPT** [comment]
Copy and pasted it but it doesn't connect to Wi-Fi still and my computer hotspot doesn't even show up...

EDIT: it still only shows up when I boot connected to LAN

**Comment by mintyleaf** [comment]
> Copy and pasted it but it doesn't connect to Wi-Fi still and my computer hotspot doesn't even show up...
> 
> EDIT: it still only shows up when I boot connected to LAN

so you downloaded it, mounted efi, deleted it, pasted the new one, rebooted, reset NVRAM, right?
idk what else can be done, since I really didn't face any issues and don't know how to investigate this)
maybe you can look to the dmesg and Console application log messages, maybe there are something interesting

**Comment by rynesPT** [comment]
I think I got the problem. It's happening to the USB wi-Fi adapter too (also tried it and didn't work). I don't have an IP address I think

Edit: Opened the laptop to check if I had the right card and it is indeed a intel 8260ngw

**Comment by mintyleaf** [comment]
> I think I got the problem. It's happening to the USB wi-Fi adapter too (also tried it and didn't work). I don't have an IP address I think
> 
> Edit: Opened the laptop to check if I had the right card and it is indeed a intel 8260ngw

can you try just another wifi network?
I'm using my pixel 3 hotspot for all the time, and it's just working fine
maybe you facing something related to hotspot <-> macOS compatibility related, idk

**Comment by rynesPT** [comment]
I tried my eduroam (university wi-fi) and my computer wi-fi with no positive results. I'll try a friend's phone and report back to you. I might consider installing Big Sur since the adaptor and drivers I used for it worked on that OS (it's a T2U Nano).

**Comment by rynesPT** [comment]
Since I was failing to make any Wi-Fi/Wi-Fi adapters work on macOS Monterey (and Big Sur because I still went back to it to check), I decided to go on Windows 11 to check my entire specs. Is something incompatible with this EFI?
[Report.zip](https://github.com/SuhailSherief/ThinkPad-x260-macOS-OpenCore/files/10127738/Report.zip)

**Comment by mintyleaf** [comment]
> Since I was failing to make any Wi-Fi/Wi-Fi adapters work on macOS Monterey (and Big Sur because I still went back to it to check), I decided to go on Windows 11 to check my entire specs. Is something incompatible with this EFI?
> [Report.zip](https://github.com/SuhailSherief/ThinkPad-x260-macOS-OpenCore/files/10127738/Report.zip)

dunno
everything almost the same, the networking and cpu part the same
this is just strange

**Comment by rynesPT** [comment]
Reinstalled Monterey using your EFI and still no luck. Was able to use Ethernet ,setup iCloud and download apps like Chrome and Spotify however Wi-Fi still doesn't work (but Bluetooth works tho)
[config.zip](https://github.com/SuhailSherief/ThinkPad-x260-macOS-OpenCore/files/10133911/config.zip)

EDIT:
1. I did setup PlatformInfo to use iCloud.
2. The Wi-Fi adapter doesn't show up on Hackintool

**Comment by mintyleaf** [comment]
> Reinstalled Monterey using your EFI and still no luck. Was able to use Ethernet ,setup iCloud and download apps like Chrome and Spotify however Wi-Fi still doesn't work (but Bluetooth works tho) [config.zip](https://github.com/SuhailSherief/ThinkPad-x260-macOS-OpenCore/files/10133911/config.zip)
> 
> EDIT:
> 
> 1. I did setup PlatformInfo to use iCloud.
> 2. The Wi-Fi adapter doesn't show up on Hackintool

Hm.. So you didn't see it like there in hackintool, right?
![image](https://user-images.githubusercontent.com/17470408/205149038-80de6b4f-c414-43bd-b66c-50574cd1a4e9.png)

How about kexts? Did everything loaded there?
![image](https://user-images.githubusercontent.com/17470408/205149731-2a68bdf2-1905-47f8-a788-d70e696bd547.png)

Yet, everything is working fine in Windows, and you definitely have an 8260 device, according to AIDA report...
Well, I completely don't know what causing that issue
Can you give me the dmesg (sudo dmesg > log.txt) output?

You can also try to replace EFI to the https://github.com/simprecicchiani/ThinkPad-T460s-macOS-OpenCore
It's pretty much the same (bluetooth disabled, as they aware of volume hash mismatch which is almost fine, you can just enable it's kext if you want to)
Maybe something new is going to pop up there, idk

**Comment by rynesPT** [comment]
![IMG_0680](https://user-images.githubusercontent.com/119418594/205154483-257929ae-92dd-4227-9feb-6f78c402a072.JPEG)
![IMG_0681](https://user-images.githubusercontent.com/119418594/205154489-2d50b0b9-865e-4a64-a69f-3c58e6295e5b.JPEG)
This is what shows up on Hackintool now at some point it showed up here but it still doesn't work.

And this is the log.txt file you asked :D Sorry I took so long but I'm still learning and thank you so much for your patience. I'll try that EFI right now!
[log.txt](https://github.com/SuhailSherief/ThinkPad-x260-macOS-OpenCore/files/10136011/log.txt)

Edit:
Booted the EFI through USB and I think it kernel panicked because it rebooted (only changed PlatflormInfo)
With your EFI, the Wi-Fi doesn't show up on Network and the USB Wi-Fi Adapter (drivers by chris1111) says Self-Assigned IP when I connect or just doesn't let me connect at all

**Comment by mintyleaf** [comment]
> ![IMG_0680](https://user-images.githubusercontent.com/119418594/205154483-257929ae-92dd-4227-9feb-6f78c402a072.JPEG) ![IMG_0681](https://user-images.githubusercontent.com/119418594/205154489-2d50b0b9-865e-4a64-a69f-3c58e6295e5b.JPEG) This is what shows up on Hackintool now at some point it showed up here but it still doesn't work.
> 
> And this is the log.txt file you asked :D Sorry I took so long but I'm still learning and thank you so much for your patience. I'll try that EFI right now! [log.txt](https://github.com/SuhailSherief/ThinkPad-x260-macOS-OpenCore/files/10136011/log.txt)
> 
> Edit: Booted the EFI through USB and I think it kernel panicked because it rebooted (only changed PlatflormInfo) With your EFI, the Wi-Fi doesn't show up on Network and the USB Wi-Fi Adapter (drivers by chris1111) says Self-Assigned IP when I connect or just doesn't let me connect at all

hmm
strange, nothing showed up related to itlwm

**Comment by rynesPT** [comment]
Maybe I didn't load it properly or messed up the installation. I have no idea what to do. :( I've tried using this, https://openintelwireless.github.io/itlwm/Troubleshooting.html#hardware-configuration, to troubleshoot and it doesn't do anything. Tried the USB Adapter I used on my previous hackintosh (a Legion Y540 with Big Sur that worked but took a ton of time to boot up due to using on a HDD) with chris1111 and I get "Self-assigned IP", tried Airport, tried itlwm and nothing works.

**Comment by mintyleaf** [comment]
> Maybe I didn't load it properly or messed up the installation. I have no idea what to do. :( I've tried using this, https://openintelwireless.github.io/itlwm/Troubleshooting.html#hardware-configuration, to troubleshoot and it doesn't do anything. Tried the USB Adapter I used on my previous hackintosh (a Legion Y540 with Big Sur that worked but took a ton of time to boot up due to using on a HDD) with chris1111 and I get "Self-assigned IP", tried Airport, tried itlwm and nothing works.

it's strange, just because for my first ever hackintosh on exact same laptop it was just copying EFI from this repo, putting macOS recovery, and it just worked and I didn't have any issues with wifi)

**Comment by rynesPT** [comment]
I tried both an Olarina raw and macOS recovery recommend by the OpenCore guide and both had the same results, it would either show networks but not connect, don't even show at all with Wi-Fi greyed out or just don't show up entirely...

**Comment by rynesPT** [comment]
Well I reinstalled Monterey again and didn't touch the config.plist to avoid any problems. And apparently it having the same behaviour as it did last time (only showing Wi-Fi when booting up with LAN and still not connecting).

**Comment by SuhailSherief** [comment]
@rynesPT did you get your wifi working bud ?

**Comment by rynesPT** [comment]
> 

Hi! I wasn’t able and decided to go back to Windows 11 in the meantime :( For some reason I didn’t get an IP (even when using chris1111’s drivers for a T2U Nano) but I did try everything mintyleaf said to do (eternally grateful for his help :D)

**Comment by SuhailSherief** [comment]
@rynesPT really sorry buddy just to make sure, did you try connecting to hidden network buddy? refer this just in case
https://openintelwireless.github.io/itlwm/FAQ.html#features

**Comment by rynesPT** [comment]
I tried connecting to my iPhone hotspot (via Wi-Fi because through USB works fine), to my primary computer hotspot and to my college dorm Wi-Fi (which I’m guessing is WPA Enterprise) and none of them worked. The Wi-Fi only searched for networks when booting up connected to LAN but it didn’t actually connect saying that the network was out of reach (even with the hotspot on top of the laptop)

**Comment by rynesPT** [comment]
and thank you for replying so quickly! :D

**Comment by SuhailSherief** [comment]
@rynesPT strange! building EFI for Ventura will update you soon buddy make sure you try that out meanwhile here's my discord シェリエフ#1423 will update you on the progress and also sort out this problem

**Comment by rynesPT** [comment]
Thank you so much! I'm looking forward to the Ventura EFI (or a Monterey solution). :D
