### ISSUE TITLE
camera doesn't work

### ISSUE THREAD

**Issue by FluttyPNG** [SuhailSherief/ThinkPad-x260-macOS-OpenCore#8]
when I try to use the built-in camera it's shows nothing on discord and I see nothing in FaceTime

**Comment by SuhailSherief** [comment]
Definitely has to do something with USBMap. Did you use EFI on the repository? please do try it! I've preconfigured the USBMap. Also refer to these if you plan to configure on own or fix it buddy :)

https://github.com/USBToolBox/tool

https://github.com/USBToolBox/kext

https://www.reddit.com/r/hackintosh/comments/n2udl3/usbtoolbox%E1%B5%87%E1%B5%89%E1%B5%97%E1%B5%83_making_usb_mapping_simpler/

**Comment by FluttyPNG** [comment]
thanks, I use te EFI on the repository but I will try to configure, maybe that is caused due to the multiple option available when the X260 was buyable

**Comment by FluttyPNG** [comment]
so, I don't know how but after a fail in the config.plist i try to boot with a backup of a config.plist, and it works, thanks for giving me the instruction to map usb

**Comment by SuhailSherief** [comment]
so you got the camera working now buddy ?
