### ISSUE TITLE
Brightness

### ISSUE THREAD

**Issue by eegipp** [SuhailSherief/ThinkPad-x260-macOS-OpenCore#9]
Hello, i use your config on my x260 i5-6300u.
But in the cold boot, birghtness key / slider is not native.
Only works native after sleep. Can you help me ?

**Comment by SuhailSherief** [comment]
So before login the brightness keys don't function for me either but on inital startup (cold boot) and after login it works. Try spamming the brightness keys after you log in just to make sure if it works. If it doesn't let me know.

**Comment by eegipp** [comment]
sorry, but in my case not works (native). 
only min or max brightness. So i can't ajust brightness.
works after my thinkpad goes to sleep.

**Comment by SuhailSherief** [comment]
can you ping me in discord buddy ? 
シェリエフ#1423

**Comment by SuhailSherief** [comment]
Using the snapshot of build 12.6.2 fixed the problem. Later builds causes issue with the brightness only. If you guys want a snapshot of 12.6.2 ping me in discord :) thanks a ton eegipp <3
